### ISSUE TITLE
为什么我的batch_size无论设多大，处理时一次最多就接收10个

### ISSUE THREAD

**Issue by Kuzhuahu** [ShannonAI/service-streamer#95]
如题

**Comment by cgr71ii** [comment]
Hi! @Kuzhuahu were you able to solve this problem? I doesn't matter the batch size I configure I can't increase the allocated GPU memory.

**Comment by cgr71ii** [comment]
Solved! I just needed to increase the value of `max_latency` in `ThreadedStreamer`.

I also needed to use [Gunicorn](https://flask.palletsprojects.com/en/2.2.x/deploying/gunicorn/) and set `--threads` to the value of my batch size in order to process all of them at once. I guess it would work with a lower value of threads too.
